// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IERC20} from "./IERC20.sol";

/// @title IAggregationRouterV5
/// @notice Minimal interface for the 1inch Aggregation Router (v5) used by the agents.
interface IAggregationRouterV5 {
    struct SwapDescription {
        IERC20 srcToken;
        IERC20 dstToken;
        address payable srcReceiver;
        address payable dstReceiver;
        uint256 amount;
        uint256 minReturnAmount;
        uint256 flags;
        bytes permit;
    }

    /// @notice Executes a swap using an off-chain generated call description.
    /// @param executor Off-chain executor address provided by 1inch API.
    /// @param desc Swap description structure describing input/output assets.
    /// @param data Calldata blob generated by the 1inch API to route the swap.
    /// @return returnAmount Amount of destination tokens received.
    /// @return gasLeft Gas remaining after swap execution (per 1inch interface).
    function swap(
        address executor,
        SwapDescription calldata desc,
        bytes calldata data
    ) external payable returns (uint256 returnAmount, uint256 gasLeft);
}


